### ISSUE TITLE
Unable to import file

### ISSUE THREAD

**Issue by gao-stu** [tematres/TemaTres-Vocabulary-Server#76]
Hi, I deployed the project.I want to use the menu -> System Management -> import  function.But there was a problem. Could you help me.
	I used docker to install the Httpd + PHP environment, I tried twice.

## first:

Installing PHP7.1.33 can start the project,but error message while importing skos-core file.

```shell
sudo docker exec httpd rpm -ivh http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
```

```shell
PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /var/www/html/tematres/common/include/inc.importSkos.php:284\nStack trace:\n#0 /var/www/html/tematres/vocab/admin.php(166): include_once()\n#1 {main}\n  thrown in /var/www/html/tematres/common/include/inc.importSkos.php on line 284, referer: http://xxx:9003/tematres/vocab/admin.php?doAdmin=import
```

Then I use yum to install php-xml, prompted no software package.  

  php -m |grep xml   only   libxml

Tabulated text: 

```shell
 Uncaught Error: Call to undefined function utf8_decode() in /var/www/html/tematres/common/include/inc.import.php:96\nStack trace:\n#0 /var/www/html/tematres/vocab/admin.php(156): include_once()\n#1 {main}\n  thrown in /var/www/html/tematres/common/include/inc.import.php on line 96, referer: http://xxx:9003/tematres/vocab/admin.php?doAdmin=import
```

## second

Php5.4.16 installed, cannot start project.

```shell
 PHP Parse error:  syntax error, unexpected 'finally' (T_STRING), expecting catch (T_CATCH) in /var/www/html/tematres/common/include/adodb5/adodb.inc.php on line 1684
```

but

```shell
but  php -m |grep xml   

libxml
xml
xmlreader
xmlrpc
xmlwriter
```

**Comment by tematres** [comment]
Hi, we cant reproduce the problem. Tematres support php 7.x. ¿Do yu use the latest version of the code?

best regards

**Comment by gao-stu** [comment]
Thank you for your reply.

I use the latest version of the code，I downloaded the code from here 
https://github.com/tematres/TemaTres-Vocabulary-Server.git   download ZIP，

 I referred to this article when deploying the project 

https://blog.csdn.net/BingZhongDeHuoYan/article/details/79424340?utm_medium=distribute.pc_aggpage_search_result.none-task-blog-2~aggregatepage~first_rank_ecpm_v1~rank_v31_ecpm-1-79424340-null-null.pc_agg_new_rank&utm_term=docker+httpd+php%E7%8E%AF%E5%A2%83&spm=1000.2123.3001.4430

 The main command used 

```shell
sudo docker pull centos/httpd

sudo mkdir -p /docker/httpd/html
sudo mkdir -p /docker/httpd/logs

sudo docker run --name httpd -d --restart always -p 80:80 -p 443:443 -v /docker/httpd/html:/var/www/html -v /docker/httpd/logs:/etc/httpd/logs centos/httpd

sudo docker exec httpd yum install -y epel-release

sudo docker exec httpd rpm -ivh http://rpms.famillecollet.com/enterprise/remi-release-7.rpm

sudo docker exec httpd yum update -y

sudo docker exec httpd yum install -y gcc make openssl openssl-devel

sudo docker exec httpd yum install -y --enablerepo=remi --enablerepo=remi-php71 php php-devel php-mbstring php-mcrypt php-mysqlnd php-pdo php-gd


sudo docker exec httpd yum clean all
sudo docker exec httpd rm -rf /var/cache/yum

sudo docker restart httpd

```



 The import function cannot be used after deployment.

 best regards
